# fly.toml app configuration file generated for kare4kids-api-main on 2025-04-04T10:05:25+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kare4kids-api-main'
primary_region = 'jnb'
console_command = '/code/manage.py shell'

[build]

[deploy]
release_command = 'sh release.sh'

[env]
PORT = '8000'
DJANGO_ENV = 'production'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

[[statics]]
guest_path = '/code/static'
url_prefix = '/static/'
